# Makefile martedi_giovedi_grasso #

martedi_giovedi_grasso: martedi_giovedi_grasso.c Makefile
	gcc -ansi -Wall -O martedi_giovedi_grasso.c -o martedi_giovedi_grasso

pulisci:
	rm -f martedi_giovedi_grasso.o

pulisci_tutto:
	rm -f martedi_giovedi_grasso martedi_giovedi_grasso.o
